version: "3"
services:
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - distributedWan
  smoc1:
      build:
        context: .
        dockerfile: smoc/Dockerfile
      networks:
        - distributedWan


networks:
  distributedWan: {}
