version: "3"
services:
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - distributedWan
  smoc1:
      build:
        context: .
        dockerfile: smoc/Dockerfile
      networks:
        - distributedWan
  smoc2:
      build:
        context: .
        dockerfile: smoc/Dockerfile
      networks:
        - distributedWan
  smoc3:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
  smoc4:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan

networks:
  distributedWan: {}
