version: "3"
services:
  smoc1:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC1}
      - QUEUE=${IPC_QUEUE_FOR_SMOC1}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC1}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC1}
  smoc2:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC2}
      - QUEUE=${IPC_QUEUE_FOR_SMOC2}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC2}
  smoc3:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC3}
      - QUEUE=${IPC_QUEUE_FOR_SMOC3}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC3}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC3}
  smoc5:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC5}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC5}
      - QUEUE=${IPC_QUEUE_FOR_SMOC5}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC5}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC5}

networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
