version: "3"
services:
  smoc1:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC1}
      - QUEUE=${IPC_QUEUE_FOR_SMOC1}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC1}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC1}
  smoc2:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC2}
      - QUEUE=${IPC_QUEUE_FOR_SMOC2}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC2}
  smoc3:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC3}
      - QUEUE=${IPC_QUEUE_FOR_SMOC3}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC3}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC3}
  smoc5:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC5}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC5}
      - QUEUE=${IPC_QUEUE_FOR_SMOC5}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC5}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC5}
  smoc4:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC4}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC4}
      - QUEUE=${IPC_QUEUE_FOR_SMOC4}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC4}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC4}
  smoc6:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC6}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC6}
      - QUEUE=${IPC_QUEUE_FOR_SMOC6}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC6}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC6}
  smoc7:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC7}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC7}
      - QUEUE=${IPC_QUEUE_FOR_SMOC7}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC7}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC7}
  smoc8:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC8}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC8}
      - QUEUE=${IPC_QUEUE_FOR_SMOC8}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC8}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC8}

networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
