version: "3"
services:
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - distributedWan
    hostname: zookeeper
  rabbitmq:
    image: 'rabbitmq:3.8.2-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - distributedWan
    hostname: rabbitmq
  smoc1:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
  smoc2:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC2}
      - QUEUE=${IPC_QUEUE_FOR_SMOC2}
      - EVENT_EXCHANGE_SMOC2=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE_SMOC2=${EVENT_QUEUE_FOR_SMOC2}
  smoc3:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    environment:
      - EXCHANGE=SMOC3_CKPT_EXCHANGE
      - QUEUE=SMOC3_CKPT_QUEUE
  smoc4:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC4}
    environment:
      - EXCHANGE=DUMMY_EXCHANGE
      - QUEUE=DUMMY_QUEUE

networks:
  distributedWan:
    ipam:
      driver: default
      config:
        - subnet: '192.17.41.0/24'
