version: "3"
services:
  smoc1:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC1}
      - QUEUE=${IPC_QUEUE_FOR_SMOC1}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC1}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC1}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc2:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC2}
      - QUEUE=${IPC_QUEUE_FOR_SMOC2}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC2}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc3:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC3}
      - QUEUE=${IPC_QUEUE_FOR_SMOC3}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC3}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC3}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc4:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC4}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC4}
      - QUEUE=${IPC_QUEUE_FOR_SMOC4}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC4}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC4}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc5:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC5}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC5}
      - QUEUE=${IPC_QUEUE_FOR_SMOC5}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC5}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC5}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc6:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC6}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC6}
      - QUEUE=${IPC_QUEUE_FOR_SMOC6}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC6}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC6}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc7:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC7}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC7}
      - QUEUE=${IPC_QUEUE_FOR_SMOC7}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC7}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC7}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc8:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC8}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC8}
      - QUEUE=${IPC_QUEUE_FOR_SMOC8}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC8}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC8}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc9:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC9}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC9}
      - QUEUE=${IPC_QUEUE_FOR_SMOC9}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC9}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC9}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc10:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC10}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC10}
      - QUEUE=${IPC_QUEUE_FOR_SMOC10}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC10}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC10}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc11:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC11}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC11}
      - QUEUE=${IPC_QUEUE_FOR_SMOC11}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC11}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC11}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc12:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC12}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC12}
      - QUEUE=${IPC_QUEUE_FOR_SMOC12}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC12}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC12}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc13:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC13}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC13}
      - QUEUE=${IPC_QUEUE_FOR_SMOC13}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC13}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC13}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc14:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC14}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC14}
      - QUEUE=${IPC_QUEUE_FOR_SMOC14}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC14}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC14}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc15:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC15}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC15}
      - QUEUE=${IPC_QUEUE_FOR_SMOC15}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC15}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC15}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  smoc16:
    build:
      context: .
      dockerfile: smoc/Dockerfile
    networks:
      - distributedWan
    hostname:  ${HOSTNAME_SMOC16}
    environment:
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC16}
      - QUEUE=${IPC_QUEUE_FOR_SMOC16}
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC16}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC16}
    tty: true
    stdin_open: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
